# Adapted from sample .travis.yml for R projects

language: r
bioc_required: true
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

after_failure: "cat /home/travis/build/joey711/phyloseq/phyloseq.Rcheck/00check.log"

notifications:
  email:
    on_success: change
    on_failure: change
