---
title: "Citing phyloseq and related tools"
---

The phyloseq R package and associated tools and documentation are provided free of charge and open-source, with the expectation that work derived from these materials will be properly cited and attributed.
The following serves as useful examples of the articles one might cite,
as well as additional links to documentation on 
phyloseq, 
its associated tools, 
and its theoretical motivations.

## Shiny-phyloseq: a phyloseq GUI Web Application

- McMurdie and Holmes (2014)
[Shiny-phyloseq: Web Application for Interactive Microbiome Analysis with Provenance Tracking](http://bioinformatics.oxfordjournals.org/content/early/2014/10/02/bioinformatics.btu616).
Bioinformatics (Oxford, England) 31(2), 282–283.

## Improved Normalization and Feature Detection

- Waste Not Your Data McMurdie and Holmes (2014) [Waste Not, Want Not: Why Rarefying Microbiome Data is Inadmissible](http://dx.plos.org/10.1371/journal.pcbi.1003531).
PLoS Computational Biology. 10(4):e1003531
- [Supplemental Materials Hosted on GitHub](http://joey711.github.io/waste-not-supplemental/)
- (2013) Pre-print hosted on the arxiv prior to publication.
[PDF version 2 (12 Dec 2013)](http://arxiv.org/pdf/1310.0424v2.pdf),
[PDF version 1 (1 Oct 2013)](http://arxiv.org/pdf/1310.0424v1.pdf).

## The phyloseq R package citation

McMurdie and Holmes (2013) phyloseq: 
[An R Package for Reproducible Interactive Analysis and Graphics of Microbiome Census Data](http://dx.plos.org/10.1371/journal.pone.0061217).
PLoS ONE. 8(4):e61217

