---
title: "Courses involving phyloseq"
date: "`r date()`"
output: 
  html_document: 
    toc: yes
    toc_depth: 2
    toc_float: true
---

<link rel="stylesheet" href="site_libs/academicons-1.7.0/css/academicons.css"/>

&nbsp;

---

# Open and Upcoming

There are a number of courses now including or featuring phyloseq. I will try and link here to the ones I know about.

---

&nbsp;

## SISMID Workshop, 2016

- [Summer Institute in Statistics, Modeling in Infectious Diseases (SISMID): (2016 July 25th to July 27th) Module 14, Introduction to Metagenomic Data Analysis](http://www.biostat.washington.edu/suminst/sismid2016/modules/MD1614)

Week 3, Session 5

Monday 8:30 AM - Wednesday 12:00 PM: Mon Jul 25 to Wed Jul 27

Instructor(s):
Alexander Alekseyenko and Paul McMurdie

This course is concerned with multivariate statistical analysis of microbiome data. We will briefly cover foundational concepts in microbial ecology, molecular biology, bioinformatics, and DNA sequencing. The main focus of the course will be on developing an understanding of multivariate analysis of microbiome data. Practical skills to be developed in this course include managing high-dimensional and structured data in metagenomics, visualization and representation of high-dimensional data, normalization, filtering, and mixture-model noise modeling of count data, as well as clustering and predictive model building. Programming will be done in R and fluency at the level of ‘SISMID/SISG Module 4: Introduction to R’ will be expected. Pre-requisites: knowledge of Module 1, Probability and Statistical Inference.


&nbsp;


## STAMPS Workshop, 2016

- Strategies and Techniques for Analyzing Microbial Population Structures (STAMPS)

Course Dates: August 3 – August 13, 2016

Deadline: April 8, 2016 (Expired!)

[Course Website](https://stamps.mbl.edu/index.php/Main_Page)

[Course Schedule](https://stamps.mbl.edu/index.php/Schedule)

Directors: Mitchell L. Sogin, MBL and David B. Mark Welch, MBL

Deep DNA sequencing using massively-parallel, next-generation technology has enabled nearly comprehensive environmental surveys that can describe the different kinds of microbes in a community and their relative abundance. These descriptions of richness and evenness make possible estimates of microbial diversity, but the size of the required data sets pose enormous computational challenges. The rapidly expanding flow of information from next generation DNA sequencing platforms has fueled healthy debate about best practices for data analysis while at the same time building a user demand for tools that can address important ecological questions. The STAMPS course will promote dialogue and the exchange of ideas between experts in analysis of metagenomic data and offer interdisciplinary bioinformatic and statistical training to practitioners of molecular microbial ecology and genomics.

Topics to be covered include but are not limited to acquisition and organization of next generation sequence data; principles of quality control of sequence data and data management; methods of taxonomic assignment and clustering of targeted gene data; assembly, functional classification and characterization of shotgun metagenomic data; statistical models for estimating microbial diversity; and microbial community comparison methodology and metrics. The workshop also includes an introduction to the Linux command-line and R statistical environments. The lectures will be augmented by a computer laboratory where students will have the opportunity to use state of the art facilities to test theoretical concepts described in the lectures series. Guided by authors of resources including CatchAll, LEfSe, mothur, Oligotyping, MetaPathways, MetaPhlAn, PhyloSeq, QIIME, USEARCH, Unifrac, and VAMPS, participants in the workshop will have the opportunity to compare different analysis techniques for molecular data, analyze their own data, and discuss their data and analyses with faculty.

The course is designed for established investigators, postdoctoral fellows and advanced graduate students from diverse biological fields. The Workshop Participants will also be given priority for acceptance into the MBL’s Workshop in Molecular Evolution that will meet the preceding week. This option will provide an opportunity to develop a stronger conceptual framework for understanding the basis of analytical tools in the STAMPS workshop.


&nbsp;


## Workshop on Genomics, 2017

- [Workshop on Genomics, Český Krumlov, Czech Republic (2017 January)](http://evomics.org/workshops/workshop-on-genomics/)

The Workshop on Genomics was developed in response to the increasing demand for training on how to effectively analyze and manage data generated by modern sequencing technologies. The Workshop curriculum includes extensive coverage of fundamental techniques required of all studies utilizing modern sequence data. This includes management and modification of modern sequence data files, using the Unix command-line and editors to manipulate sequence data files, assembly (both mapping and de novo) and best practices for sequence data generation. The second-half of the Workshop is devoted to specific sub-disciplines within the genomic sciences. While these topics may change from Workshop to Workshop, efforts are made to devote significant amounts of time to techniques being used widely in the field (e.g. transcriptomics, genome assembly, metagenomics).

A majority of the schedule is dedicated to hands-on learning activities designed by faculty and the workshop team. This interactive experience provides Workshop participants with the practical experience required to meet the challenges presented by modern genomic sciences.


&nbsp;


---

# Concluded for 2016


&nbsp;


## Workshop on Genomics, 2016

- [Workshop on Genomics, Cesky Krumlov, Czech Republic (2016 Jan 10 - 23)](http://evomics.org/workshops/workshop-on-genomics/2016-workshop-on-genomics-cesky-krumlov/)



&nbsp;


# Concluded for 2015

## Workshop on Metagenomics (Harvard)

- [Harvard University Workshop on Metagenomics (2015 Sept 14 - 18)](http://evomics.org/workshops/harvard-university-workshops/2015-harvard-university-workshop-on-metagenomics/)

A week-long workshop focused exclusively on the analysis of metagenomic data.  This intensive, hands-on course will feature morning and afternoon sessions taught by expert faculty and technical assistants from the Broad, Ragon Institute, Harvard School of Public Health, Stanford University and Washington University, St. Louis.  All participants will acquire fundamental computational skills, appropriate study design, data interpretation, and overall literacy in bioinformatics.

When: 2015 14-18, September : Morning Sessions 9:00 – 12:00 | Afternoon Sessions 2:00 – 5:00

Where: Joseph B. Martin Conference Center Harvard Medical School 77 Avenue Louis Pasteur Boston, MA 02115.


&nbsp;


## SISMID Workshop, 2015

- [Summer Institute in Statistics, Modeling in Infectious Diseases (SISMID): Metagenomics Module](http://www.biostat.washington.edu/suminst/sismid/modules)


&nbsp;

## STAMPS Workshop, 2015

- [Strategies and Techniques for Analyzing Microbial Population Structure (STAMPS)](https://stamps.mbl.edu/index.php/Main_Page)

Directors: 

David Mark Welch Marine Biological Laboratory

Mitch Sogin Marine Biological Laboratory

Course Date: August 5 - August 15, 2015

Twitter hash: #STAMPS15

Deep DNA sequencing using massively-parallel, next-generation technology has enabled nearly comprehensive environmental surveys that can describe the different kinds of microbes in a community and their relative abundance. These descriptions of richness and evenness make possible estimates of microbial diversity, but the size of the required data sets pose enormous computational challenges. The rapidly expanding flow of information from next generation DNA sequencing platforms has fueled healthy debate about best practices for data analysis while at the same time building a user demand for tools that can address important ecological questions. The STAMPS course will promote dialogue and the exchange of ideas between experts in analysis of metagenomic data and offer interdisciplinary bioinformatic and statistical training to practitioners of molecular microbial ecology and genomics.

Topics to be covered include but are not limited to next-generation strategies for analysis of microbial communities; acquisition and organization of next generation sequence data; principles of quality control of sequence data; the theory of cluster and rarefaction analyses; taxonomic assignments for high-throughput data; statistical models for estimating microbial diversity; microbial community comparison methodology and metrics; and analysis of shotgun metagenomic data. The lectures will be augmented by a computer laboratory where students will have the opportunity to use state of the art facilities to test theoretical concepts described in the lectures series.


