---
title: "phyloseq Frequently Asked Questions (FAQ)"
author: "Paul J. McMurdie"
date: "`r date()`"
output: 
  html_document: 
    fig_caption: yes
    fig_height: 9
    fig_width: 9
    theme: readable
    toc: yes
---


# I tried reading my biom file using phyloseq, but it didn’t work. What’s wrong?

## biom-format Versions 1 and 2

## HDF5 (Version 2.0) biom-format has beta support...
It is currently supported in the development version of phyloseq,
via the new beta/development package called "biomformat"
on BioC and GitHub:

https://github.com/joey711/biomformat

## Not every data component is included in .biom files

Even though the biom-format supports the self-annotated inclusion
of major components like that taxonomy table and sample data table,
many tools that generate biom-format files
(like QIIME, MG-RAST, mothur, etc.)
do not export this data, even if it is provided as an input file.
Furthermore, even though I have proposed it to the biom-format team,
there is currently know support (or timeline for support) 
for inclusion of a phylogenetic tree within a ".biom" file.

A number of tutorials are available
demonstrating how one can add components to a phyloseq object
after it has been created/imported.
The following tutorial is especially relevant
http://joey711.github.io/phyloseq-demo/import-biom-sd-example.html

## Other issues related the biom-format

There are a number of different Issue Tracker posts
discussing this format with respect to phyloseq:

https://github.com/joey711/phyloseq/issues/302

https://github.com/joey711/phyloseq/issues/272

https://github.com/joey711/phyloseq/issues/392

### [Issue 443](https://github.com/joey711/phyloseq/issues/443)
has details for updated format

### Details on [HDF5](https://www.hdfgroup.org/HDF5/doc/UG/index.html)


---

# `microbio_me_qiime()` returned an error. What’s wrong?

## The QIIME-DB Server is Permanently Down.

Users are suggested to migrate their queries over to Qiita.

Indeed, the previous link to
[microbio.me/qiime](http://www.microbio.me/qiime/index.psp)
now sends users to the new Qiita website.

## An interface to Qiita is Planned.

Stay tuned. The Qiita API needs to be released by the Qiita developers first.


---

# I want a custom phyloseq graphic with the following specification...

Great!

## psmelt and ggplot2

Originally an internal phyloseq tool used by several phyloseq `plot_` functions,
the `psmelt` function converts your phyloseq object into
a `data.frame` that is very friendly for defining a custom ggplot2 graphic.
There are lots of great documentation examples for ggplot2 in general,
and phyloseq in particular. 

## Submit a Pull Request (Advanced)

If your new custom plot function is awesome and you think others might use it,
add it to the "plot-methods.R" function and submit a pull request on GitHub.
Please include example and test code. 
I'll try and add it to the package by the next release.
I will also give you authorship cred in the function doc.


---

# There’s a typo in the documentation at this location

This is something you can solve yourself! 
Use GitHub, send a pull request!
It will actually take longer to explain in an email -- and less useful --
than to just fix the documentation in the relevant roxygen header 
and submite a pull request.


---

# I read “Waste Not, Want Not” and I use DESeq2 to normalize my data, but...

## now there are negative numbers

## I get an error regarding geometric mean

## pseudocounts are not appropriate for my data

https://github.com/joey711/phyloseq/issues/445

## I don’t know how to test for differential abundance now. How do I do that?

## I’m scared that the Negative Binomial doesn’t fit my data well

---

# I was wondering if you could help me analyze my data. It has the following study design...



