# http://rmarkdown.rstudio.com/rmarkdown_websites.html
rmarkdown::render_site()

# Cleaning Up

# To clean up all of the files generated via render_site 
# you can call the clean_site function, which will remove 
# all files generated by rendering your site’s markdown documents
# including knitr _cache directories. You can specify the 
# preview = FALSE option to just list the files to be removed 
# rather than actually removing them:
  
# list which files will be removed
# rmarkdown::clean_site(preview = TRUE)

# actually remove the files
# rmarkdown::clean_site()
